version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 3000:3000
    depends_on: 
      - backend
    networks:
      - proj_network

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 5000:5000
    networks:
      - proj_network

networks:
    proj_network:
        name: proj_network