name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome

jobs:
  test:
    runs-on: ubuntu-latest
    name: Action Test
    steps:
        - uses: actions/checkout@v1
        - uses: testingbot/testingbot-tunnel-action@v1.1.0
          with:
            key: ${{ secrets.TB_KEY }}
            secret: ${{ secrets.TB_SECRET }}
            tunnelIdentifier: github-action-tunnel

        - name: "Install Dependencies"
          run: npm install

        - name: "Run Test"
          run: npm run test
          env:
            TB_KEY: ${{ secrets.TB_KEY }}
            TB_SECRET: ${{ secrets.TB_SECRET }}