name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    name: Test 
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Build and test client
      working-directory: client
      run: |
        npm install
    - name: Build and test API
      working-directory: api
      run: |
        chmod -R a+rwx chromedriver.exe
        npm install
        npm start &
        npm test
