name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    
    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}
        options: --shm-size=2gb
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Build and test client
      working-directory: client
      run: |
        npm install
    - name: Build and test API
      working-directory: api
      run: |
        npm install
        npm start &
        npm test
