name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    name: <Any name> 
    steps:
    - name: <e.g. Selenoid >
      uses: ajinx/selenoid@v2
    - uses: actions/checkout@v2
    - run: npm ci  
    - name: <Any test job run name>
      run: <Test execution command e.g. mvn test, npm test etc>
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Build and test client
      working-directory: client
      run: |
        npm install
    - name: Build and test API
      working-directory: api
      run: |
        npm install
        npm start &
        npm test
